### ISSUE TITLE
Fix default logger

### ISSUE THREAD

**Issue by inoryy** [inoryy/reaver#18]
Current default is essentially `/dev/null` which is probably not the expected behavior for people trying to run reaver from inside their own codebase.

**Comment by GabrielZH** [comment]
So is this the cause of the AttributeError: 'AdvantageActorCriticAgent' object has no attribute 'logger' when trying to run a quickstart currently?

**Comment by inoryy** [comment]
Oh, seems I've broken it with some of the recent changes. As a temporary workaround you can manually initialize the `/dev/null` logger via `agent.logger = rvr.utils.Logger()`. Alternatively see how the full `StreamLogger` is initialized [here](https://github.com/inoryy/reaver-pysc2/blob/master/reaver/run.py#L79).

**Comment by GabrielZH** [comment]
Thank you so much!

**Comment by inoryy** [comment]
Enabled `StreamLogger` by default with sensible configs in `2.1.5`.
