### ISSUE TITLE
How to watch full graphics replay

### ISSUE THREAD

**Issue by jaejaywoo** [inoryy/reaver#21]
Hello, 

Can you please elaborate further on how you recorded the full graphics replay? I am currently using SC2 Linux version 4.1.2 and have been trying to watch the full graphics replay on Windows by logging into the Battle.net, but I keep failing to do so presumably because of the version difference. You briefly mentioned on the README about it, but can you please explain it in a little more detail on how you did it?

Thank you.

**Comment by inoryy** [comment]
Hello,

On windows it should work out of the box as the windows client is able to download required version. When you navigate to the replay in-game it should say something like "This replay is from another version, StarCraft II will download and log you out, proceed?".
