### ISSUE TITLE
Dimension of screen feature

### ISSUE THREAD

**Issue by kimbring2** [inoryy/reaver#30]
Hello,

I am trying to apply Relational Network in DefeatRoaches environment using the code you uploaded.
The size of the screen feature is 16, but is it too small to affect performance?

I want to know that the performance graph shown on the web page is the performance when using the size of the screen feature.

From Dohyeong Kim

**Comment by inoryy** [comment]
Yes, 16px is enough to achieve the performance listed. Going up to 32 or 64 is mostly a question of computational resources, on most minigames, even the sample efficiency remains the same, it just takes much longer to gather them.
