### ISSUE TITLE
I train under the ubuntu

### ISSUE THREAD

**Issue by songwaimai** [inoryy/reaver#33]
Dear Inorry,
  Thanks your sharing, I can learn a lot. Now I have trained four minigames and they are consistent with your results. But the other three minigames can not run. the error is id 1/id 17 unknown. I use gtx1080 ti , ubuntu16.04. I wonder if it has something to do with it?

**Comment by inoryy** [comment]
It's definitely not related to your GPU or OS. Did you install pysc2 from master branch?

**Comment by songwaimai** [comment]
yes，I install pysc2 from master branch.  When I run the program using map of FindAndDefeatZerglings, ValueError: Unknown ability_id: 1, type: cmd_quick. Likely a bug. When i run the program using map of CollectMineralsAndGas and BuildMarines, ValueError: Unknown ability_id: 17, type: cmd_quick. Likely a bug.

**Comment by inoryy** [comment]
What SC2 version do you use?

**Comment by songwaimai** [comment]
SC2 version is 3.16.1，maybe this reason?

**Comment by inoryy** [comment]
Yes, Reaver requires SC2 version 4.1+.

**Comment by songwaimai** [comment]
Thank u very much!
