### ISSUE TITLE
Question about performance on BuildMarines

### ISSUE THREAD

**Issue by XinyiYS** [inoryy/reaver#34]
Hi @inoryy , in addition to the results on these minigames. I notice there isn't any results on BuildMarines, may I ask if there is an update or if there is a planned follow-up? 

By the way, awesome repo!

**Comment by inoryy** [comment]
Hello Michael,

Yes, BuildMarines is difficult to solve end-to-end. Don't have a follow-up planned at the moment either unfortunately as I am busy at work now.

Thank you for the kind words! :)

**Comment by XinyiYS** [comment]
Got it. Cheers!
