### ISSUE TITLE
How to use the Plot.py util file?

### ISSUE THREAD

**Issue by QwertyMaster00** [inoryy/reaver#36]
Hi @inoryy ,
I am trying to figure out how to figure out how to use this plot.py file in your utils folder, I want more data on the experiment I am running. 

Sorry if this is basic, but could you explain how you use this util file?
As in do I have to call this from command line or a python file?

**Comment by inoryy** [comment]
Hello,

Yep, you need to run it from the command line, pointing to the results directory containing summaries.

Note that to keep track of the training progress you're better off just using tensorboard as the summaries contain much more info than what's generated by the plot util, which I mostly used to create the side-by-side figures in the readme.

**Comment by QwertyMaster00** [comment]
Awesome thanks for the helpful information. I will look into using tensorboard for data visualization.

Also since I have no other way to contact you, I wanted to mention I am streaming on twitch.tv  a reaver experiment with the username qwertymaster00. I have a goal of creating a balanced TvZ system but I am still working with Reaver to see how I can do this. I have had some limited success and I am now working on a larger GPU. I am always looking for help or advice on how to optimize. Thanks again for building this out, I am having a lot of fun with it

**Comment by inoryy** [comment]
That's awesome to hear!
If you have any specific questions, feel free to reach out via the email in my profile.

**Comment by QwertyMaster00** [comment]
Great, I sure will!
